import Head from "next/head";
import Image from "next/image";
import { Barlow } from "next/font/google";

const font = Barlow({
  subsets: ["latin"],
  weight: "400",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Lilium - Florals by Renee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full w-full p-16">
        <div className="flex mx-auto flex-col md:flex-row h-full w-full items-center justify-center p-4 gap-6">
          <div className="h-[400px] w-[400px] bg-gray-300 rounded-md" />
        </div>
      </main>
    </>
  );
}
